quarkus.package.jar.type=uber-jar

# App
quarkus.http.port=8081
quarkus.application.name=Car Rental
quarkus.banner.path=banner.txt

# DB
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/car-rental
quarkus.datasource.username=admin
quarkus.datasource.password=admin

# Mongo
quarkus.mongodb.connection-string = mongodb://localhost:27017

# Kafka
kafka.bootstrap.servers=localhost:9092
# Read
mp.messaging.incoming.payment-topic-in.connector=smallrye-kafka
mp.messaging.incoming.payment-topic-in.topic=payment-topic
mp.messaging.incoming.payment-topic-in.group.id=car-rental
mp.messaging.incoming.payment-topic-in.auto.offset.reset=earliest
# Write
mp.messaging.outgoing.payment-topic-out.connector=smallrye-kafka
mp.messaging.outgoing.payment-topic-out.topic=payment-topic
# Write perf.
mp.messaging.outgoing.payment-topic-out.acks=1
mp.messaging.outgoing.payment-topic-out.linger.ms=5
mp.messaging.outgoing.payment-topic-out.batch.size=32768
mp.messaging.outgoing.payment-topic-out.compression.type=snappy

# Log
quarkus.log.level=INFO
#quarkus.log.category."org.hibernate.SQL".level=DEBUG
#quarkus.log.category."org.hibernate.SQL".min-level=DEBUG
#quarkus.log.category."org.hibernate.orm.jdbc.bind".level=TRACE
#quarkus.log.category."org.hibernate.orm.jdbc.bind".min-level=TRACE
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".min-level=TRACE

# Jwt
quarkus.smallrye-jwt.enabled=true

# Jwt - Build
smallrye.jwt.sign.key.location=privateKey.pem

# Jwt - Consume
mp.jwt.token.header=Authorization
mp.jwt.verify.issuer=https://car-rental.acme.org/user-service
mp.jwt.verify.publickey.location=publicKey.pem

# Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger
quarkus.smallrye-openapi.path=/q/docs
mp.openapi.scan.disable=true
mp.openapi.extensions.smallrye.remove-unused-schemas.enable=false

# Native
quarkus.native.resources.includes=banner.txt,publicKey.pem,privateKey.pem
