quarkus.package.jar.type=uber-jar

# App
quarkus.http.port=8081
quarkus.application.name=Car Rental
quarkus.banner.path=banner.txt

# DB
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/car-rental
quarkus.datasource.username=admin
quarkus.datasource.password=admin

# Log
quarkus.log.level=INFO
#quarkus.log.category."org.hibernate.SQL".level=DEBUG
#quarkus.log.category."org.hibernate.SQL".min-level=DEBUG
#quarkus.log.category."org.hibernate.orm.jdbc.bind".level=TRACE
#quarkus.log.category."org.hibernate.orm.jdbc.bind".min-level=TRACE
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".min-level=TRACE

# Jwt
quarkus.smallrye-jwt.enabled=true

# Jwt - Build
smallrye.jwt.sign.key.location=privateKey.pem

# Jwt - Consume
mp.jwt.token.header=Authorization
mp.jwt.verify.issuer=https://car-rental.acme.org/user-service
mp.jwt.verify.publickey.location=publicKey.pem

# Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger
quarkus.smallrye-openapi.path=/q/docs
mp.openapi.scan.disable=true
mp.openapi.extensions.smallrye.remove-unused-schemas.enable=false

# Native
quarkus.native.resources.includes=banner.txt,publicKey.pem,privateKey.pem
