---
- name: PSQL DDL IMPORT
  community.postgresql.postgresql_query:
    login_host: "{{ ansible_host }}"
    login_port: "{{ psql.host.port }}"
    login_user: "{{ psql.db.user }}"
    login_password: "{{ psql.db.password }}"
    db: "{{ psql.db.name }}"
    query: "{{ lookup('file', role_path + '/files/ddl/user/' + ddl) }}"
  loop: "{{ psql.files.user.ddl }}"
  loop_control:
    loop_var: ddl